### ISSUE TITLE
It may be worth you taking a look at this dicussion

### ISSUE THREAD

**Issue by REMC19** [ktgw0316/LightZone-backup#25]
Hi Masahiro
It may be worth you reading this discussion on Pixls, please read it all the way through - as there is the odd negative comment on there, but you will also see that people do still like the software, but are worried that it was going away.
https://discuss.pixls.us/t/new-lightzone-release-4-2/17120/47
I don't know if you have any interest in working with any other developers, but several appear to frequent Pixls.us and most of them seem to be quite happy with sharing ideas and code between each others projects - so that might be a way to take a bit of the weight of developing the program all by yourself away.

**Comment by sfink16** [comment]
@REMC19 Please consider putting this into the Discussion tab by clicking the "New Discussion" button.  This will free Masahiro from replying to it since he has indicated that English is not his best language to write in.  Plus, it is a discussion, not really an issue.  See https://github.com/ktgw0316/LightZone/issues/24#issuecomment-1341786760(url) of his language barrier concerns.

**Comment by REMC19** [comment]
Moved to discussion as suggested.
